ComplaintMngSys/Models/UserAccountViewModel/ResetPasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ComplaintMngSys.Models.UserAccountViewModel
{
    public class ResetPasswordViewModel
    {
        public string ApplicationUserId { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Old Password")]
        [DataType(DataType.Password)]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 3)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("NewPassword", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
        public string Code { get; set; }
    }
}

ComplaintMngSys/Models/UserProfile.cs
using System;

namespace ComplaintMngSys.Models
{
    public class UserProfile : EntityBase
    {
        public Int64 UserProfileId { get; set; }
        public string ApplicationUserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string PasswordHash { get; set; }
        public string ConfirmPassword { get; set; }
        public string OldPassword { get; set; }
        public string ProfilePicture { get; set; } = "/upload/blank-person.png";
        
    }
}

ComplaintMngSys/Controllers/UserProfileController.cs
using ComplaintMngSys.Data;
using ComplaintMngSys.Models;
using ComplaintMngSys.Models.UserAccountViewModel;
using ComplaintMngSys.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;

namespace ComplaintMngSys.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class UserProfileController : Controller
    {
        private readonly IRoles _roles;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ICommon _iCommon;

        public UserProfileController(UserManager<ApplicationUser> userManager,
            ApplicationDbContext context,
            RoleManager<IdentityRole> roleManager,
            IRoles roles,
            ICommon iCommon)
        {
            _context = context;
            _roleManager = roleManager;
            _userManager = userManager;
            _roles = roles;
            _iCommon = iCommon;
        }

        [Authorize(Roles = Pages.MainMenu.UserProfile.RoleName)]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var _ApplicationUser = await _userManager.FindByEmailAsync(HttpContext.User.Identity.Name);
            UserProfileCRUDViewModel _UserProfileCRUDViewModel = new UserProfileCRUDViewModel();
            if (_ApplicationUser.Id != null)
            {
                _UserProfileCRUDViewModel = _context.UserProfile.Where(x => x.ApplicationUserId == _ApplicationUser.Id).SingleOrDefault();
            }
            return View(_UserProfileCRUDViewModel);
        }

        [HttpGet]
        public IActionResult EditUserProfile(int id)
        {
            return PartialView("_EditUserProfile", _iCommon.GetByUserProfile(id));
        }

        [HttpPost]
        public async Task<IActionResult> EditUserProfile(UserProfileCRUDViewModel _UserProfileCRUDViewModel)
        {
            try
            {
                UserProfile _UserProfile = _iCommon.GetByUserProfile(_UserProfileCRUDViewModel.UserProfileId);

                _UserProfile.FirstName = _UserProfileCRUDViewModel.FirstName;
                _UserProfile.LastName = _UserProfileCRUDViewModel.LastName;
                _UserProfile.PhoneNumber = _UserProfileCRUDViewModel.PhoneNumber;
                _UserProfile.Address = _UserProfileCRUDViewModel.Address;
                _UserProfile.Country = _UserProfileCRUDViewModel.Country;

                if (_UserProfileCRUDViewModel.ProfilePicture != null)
                    _UserProfile.ProfilePicture = "/upload/" + _iCommon.UploadedFile(_UserProfileCRUDViewModel.ProfilePicture);

                _UserProfile.ModifiedDate = DateTime.Now;
                _UserProfile.ModifiedBy = HttpContext.User.Identity.Name;
                var result2 = _context.UserProfile.Update(_UserProfile);
                await _context.SaveChangesAsync();
                TempData["successAlert"] = "User info Updated Successfully. User Name: " + _UserProfileCRUDViewModel.Email;
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpGet]
        public async Task<IActionResult> ResetPassword(string id)
        {
            var _ApplicationUser = await _userManager.FindByIdAsync(id);
            ResetPasswordVM _ResetPasswordVM = new ResetPasswordVM();
            _ResetPasswordVM.ApplicationUserId = _ApplicationUser.Id;
            return PartialView("_ResetPassword", _ResetPasswordVM);
        }

        [HttpPost]
        public async Task<IActionResult> ResetPassword(ResetPasswordVM vm)
        {
            var _ApplicationUser = await _userManager.FindByIdAsync(vm.ApplicationUserId);
            if (vm.NewPassword.Equals(vm.ConfirmPassword))
            {
                var result = await _userManager.ChangePasswordAsync(_ApplicationUser, vm.OldPassword, vm.NewPassword);
                if (result.Succeeded)
                    TempData["successAlert"] = "Change Password Succeeded. User name: " + _ApplicationUser.Email;
                else
                {
                    string errorMessage = string.Empty;
                    foreach (var item in result.Errors)
                    {
                        errorMessage = errorMessage + " " + item.Description;
                    }
                    TempData["errorAlert"] = errorMessage;
                }
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

ComplaintMngSys/Views/UserProfile/Index.cshtml
@model ComplaintMngSys.Models.UserAccountViewModel.UserProfileCRUDViewModel

@{
    ViewData["Title"] = "User Profile";
}

<div class="wrapper">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h4><b>User Profile</b></h4>
        </div>
        <br />
        <input type="hidden" asp-for="UserProfileId" />
        <input type="hidden" asp-for="ApplicationUserId" />
        <div class="col-lg-10">
            <fieldset>
                <table class="ItemTranTable" border="1" style=" width:100%;margin:1px auto;">
                    <tr>
                        <th>Profile Picture</th>
                        <td>
                            <div class="user-panel mt-2 pb-2 mb-2 d-flex">
                                <div class="image">
                                    <img src="@Model.ProfilePicturePath" class="img-circle elevation-1"
                                        alt="User Image">
                                </div>
                                <div class="info">
                                    <a href="#" class="d-block" onclick=ViewUserImage('@Model.ProfilePicturePath')>
                                        @Model.FirstName @Model.LastName
                                    </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th>First Name</th>
                        <td>@Model.FirstName</td>
                    </tr>
                    <tr>
                        <th>Last Name</th>
                        <td>@Model.LastName</td>
                    </tr>
                    <tr>
                        <th>Phone Number</th>
                        <td>@Model.PhoneNumber</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>@Model.Email</td>
                    </tr>
                    <tr>
                        <th>Address</th>
                        <td>@Model.Address</td>
                    </tr>
                    <tr>
                        <th>Country</th>
                        <td>@Model.Country</td>
                    </tr>
                    <tr>
                        <th>Created Date</th>
                        <td>@Model.CreatedDate</td>
                    </tr>
                    <tr>
                        <th>Modified Date</th>
                        <td>@Model.ModifiedDate</td>
                    </tr>
                    <tr>
                        <th>Created By</th>
                        <td>@Model.CreatedBy</td>
                    </tr>
                    <tr>
                        <th>Modified By</th>
                        <td>@Model.ModifiedBy</td>
                    </tr>
                    <tr>
                        <th>Cancelled</th>
                        <td>@Model.Cancelled</td>
                    </tr>
                </table>
                <br />
                <div class="form-group">
                    <button class="btn btn-success" id="EditUserProfile"
                        onclick="EditUserProfile(document.getElementById('UserProfileId').value)">
                        Edit User Profile
                    </button>
                    <button class="btn btn-danger" id="ResetPassword" onclick="ResetPassword()">Reset Password</button>
                </div>
            </fieldset>
        </div>
        <br /><br />
        <div class="col-lg-10">
            <partial name="~/Views/UIComponents/_bootstrapAlert.cshtml" />
        </div>
    </div>
</div>

<script src="~/js/UserProfile/UserProfile_CRUD.js"></script>

ComplaintMngSys/Views/UserProfile/_EditUserProfile.cshtml
@model ComplaintMngSys.Models.UserProfile

<div>
    <div class="row">
        <div class="col-md-12">
            <form id="EditUserProfile" enctype="multipart/form-data" asp-controller="UserProfile" asp-action="EditUserProfile" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="UserProfileId" />
                <input type="hidden" asp-for="ApplicationUserId" />
                <div class="col-sm-12">
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" id="FirstName" class="form-control" type="text" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" type="text" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" id="lblPhoneNumber" class="control-label"></label>
                        <input asp-for="PhoneNumber" id="PhoneNumber" class="form-control" type="tel" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" type="text" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Country" class="control-label"></label>
                        <input asp-for="Country" class="form-control" type="text" />
                        <span asp-validation-for="Country" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <span class="control-fileupload">
                            <label for="file">Choose a file :</label>
                            <input type="file" asp-for="ProfilePicture" name="ProfilePicture" id="customFile" />
                        </span>
                        <p>&nbsp;</p>
                    </div>

                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" type="email" readonly />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CreatedDate" class="control-label"></label>
                        <input asp-for="CreatedDate" class="form-control" type="date" readonly />
                        <span asp-validation-for="CreatedDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-info">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

ComplaintMngSys/Views/UserProfile/_ResetPassword.cshtml
@model ComplaintMngSys.Models.UserAccountViewModel.ResetPasswordVM

<div>
    <div class="row">
        <div class="col-md-12">
            <form id="ResetPassword" asp-controller="UserProfile" asp-action="ResetPassword" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ApplicationUserId" id="ApplicationUserId_RP" />

                <div class="form-group">
                    <label asp-for="OldPassword" class="control-label"></label>
                    <input asp-for="OldPassword" class="form-control" type="password" />
                    <span asp-validation-for="OldPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="NewPassword" class="control-label"></label>
                    <input asp-for="NewPassword" class="form-control" type="password" />
                    <span asp-validation-for="NewPassword" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="control-label"></label>
                    <input asp-for="ConfirmPassword" class="form-control" type="password" />
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-info">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>